### ISSUE TITLE
New automation to create events across channels (google calendar & discord)

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/deviras#17]
### Use-case

- AMAs
- Weekly Discussions

Both are added to our [Google calendar](https://developersindia.in/events-calendar/) and an event is created on our discord server.

### Ask

- The problem is that admins have to manually add events to either discord or google calendar.
- The ask is to have a script that creates an event on both platforms in one go
- The script should accept following details:
   - Date/Time for event in IST
   - Title of the event
   - Body explaining more about the event. Preferably with some markup?
   - Location, where the event will take place

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Rancho-rachit** [comment]
self-assign :hand:

**Comment by Bhupesh-V** [comment]
> self-assign ✋

Done, feel free to create a draft-pr for an early feedback!

**Comment by Rancho-rachit** [comment]
@Bhupesh-V , have a look.

#18
