### ISSUE TITLE
Ability to post weekly/bi-weekly job threads (new script)

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/deviras#8]
### Feature details?

Since developersIndia now have an [official job board](https://developersindia.in/job-board/), we would like to regularly post about new jobs to our subreddit.

We can consume the job board's RSS feed for this

```
https://developersindia.in/?feed=job_feed&job_types=freelance%2Cfull-time%2Cinternship%2Cpart-time&search_location&job_categories
```

Couple of things to note:
- let's leave Reddit post title & body configurable via ENV vars (if possible).
- Remember to not post jobs that have already been posted. Use a local JSON file to store data.
- Each new job post will be a comment on this newly created post. Each comment will have: 
   - Job Title - [Company Name]
   - Summary of Job
   - Permalink of this job to developersIndia site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by git-bruh** [comment]
Hey, I can probably help with this. AFAICT, the script just has to make a single container post per week and post comments on that post corresponding to new job postings, is that correct? Also, is this going to be integrated in a github action so that it could be used by say, a CRON job to get new job postings for the week?

**Comment by Bhupesh-V** [comment]
> Hey, I can probably help with this. AFAICT, the script just has to make a single container post per week and post comments on that post corresponding to new job postings, is that correct? Also, is this going to be integrated in a github action so that it could be used by say, a CRON job to get new job postings for the week?

1. The post will resemble this example post (Structure wise) https://www.reddit.com/r/developersIndia/comments/10tnhfi/dont_miss_out_on_these_job_opportunities_weekly/.
3. Yes, we will automate the execution using cron expressions on actions, ([example](https://github.com/developersIndia/deviras/blob/93928f88dc7d4f784aeff3bcfa7f0bd335cb1dd5/.github/workflows/python-app.yml#L6))

LMK if you are interested to work on this.

**Comment by git-bruh** [comment]
Yeah I'd like to work on it, shouldn't take too much time
